---
name: mdformat-myst
description: Mdformat plugin that changes target specification to MyST.
homepage: https://github.com/executablebooks/mdformat-myst
licenses:
  - MIT
languages:
  - Markdown
categories:
  - Formatter

source:
  id: pkg:pypi/mdformat_myst@0.1.5

bin:
  mdformat: pypi:mdformat
